version: 3

tasks:
  default:
    desc: Run the default task
    cmds:
      - task --list

  setup:
    desc: Create the local development environment
    cmds:
      - task: python-setup

  python-setup:
    desc: Create Python virtualenv and install dependencies
    cmds:
      - uv venv
      - uv sync
    sources:
      - pyproject.toml
    generates:
      - ".venv/*"

  test:
    desc: Run all tests
    deps:
      - setup
    cmds:
      - "uv run --frozen python -m pytest -v {{.CLI_ARGS}}"

  lint:
    desc: Lint the Python code
    deps:
      - setup
    cmds:
      - "uv run --frozen ruff check ."
      - "uv run --frozen pyright ."

  format:
    desc: Format the Python code
    deps:
      - setup
    cmds:
      - "uv run --frozen ruff format ."
      - "uv run --frozen ruff check --fix-only ."

  clean:
    desc: Clean the project
    cmds:
      - rm -rf tmp
      - rm -rf .venv
      - rm -rf .pytest_cache
      - rm -rf .ruff_cache

  install:
    desc: Install the tool globally using uv
    cmds:
      - uv tool install .
      - echo "✓ Installed globally. Run 'contiamo-release-please' from anywhere."

  uninstall:
    desc: Uninstall the globally installed tool
    cmds:
      - uv tool uninstall contiamo-release-please
      - echo "✓ Uninstalled globally."

  help:
    desc: Show usage examples for contiamo-release-please
    silent: true
    cmds:
      - |
        echo "Contiamo Release Please - Usage Examples"
        echo "========================================="
        echo ""
        echo "Version Determination:"
        echo "  uv run contiamo-release-please next-version"
        echo "  uv run contiamo-release-please next-version --verbose"
        echo "  uv run contiamo-release-please next-version --config /path/to/config.yaml"
        echo ""
        echo "Changelog Generation:"
        echo "  uv run contiamo-release-please generate-changelog"
        echo "  uv run contiamo-release-please generate-changelog --dry-run --verbose"
        echo "  uv run contiamo-release-please generate-changelog --output CHANGES.md"
        echo ""
        echo "File Version Bumping:"
        echo "  uv run contiamo-release-please bump-files"
        echo "  uv run contiamo-release-please bump-files --dry-run --verbose"
        echo ""
        echo "Release Branch Creation:"
        echo "  uv run contiamo-release-please release"
        echo "  uv run contiamo-release-please release --dry-run --verbose"
        echo "  uv run contiamo-release-please release --config /path/to/config.yaml"
        echo ""
        echo "Git Tag Creation (After Merging Release PR):"
        echo "  uv run contiamo-release-please tag-release"
        echo "  uv run contiamo-release-please tag-release --dry-run --verbose"
        echo "  uv run contiamo-release-please tag-release --config /path/to/config.yaml"
        echo ""
        echo "General Help:"
        echo "  uv run contiamo-release-please --help"
        echo "  uv run contiamo-release-please next-version --help"
        echo "  uv run contiamo-release-please generate-changelog --help"
        echo "  uv run contiamo-release-please bump-files --help"
        echo "  uv run contiamo-release-please release --help"
        echo "  uv run contiamo-release-please tag-release --help"
